### ISSUE TITLE
New endpoint for messaging

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-restAPI-plugin#9]
...Migrated from [Ignite Jira OF-1074](https://issues.igniterealtime.org/browse/OF-1074)...

## Todo:

- [ ] It is possible to write a message to specific user
- [ ] It is possible to write a message to specific user group
- [ ] It is possible to write a message to specific group chat

(from server)

**Comment by Beat-YT** [comment]
I made a pull request 

✅  It is possible to write a message to specific user

https://github.com/igniterealtime/openfire-restAPI-plugin/pull/87
